<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Siswa;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $siswa = Siswa::insert([
            [
                'nama' => 'Abu Bakar Tsabit Ghufron', 
                'nis' => '20388',
                'gender' => 'L',
                'rombel' => 'SijaA',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'tsabit@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Mutiara Sekar Kinasih', 
                'nis' => '20431',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Bantul',
                'kontak' => '81234567890',
                'email' => 'mutiara@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Ade Zaidan Althaf', 
                'nis' => '20390',
                'gender' => 'L',
                'rombel' => 'SijaA',
                'alamat' => 'Gunungkidul',
                'kontak' => '81234567890',
                'email' => 'ade@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Arya Eka Rahmat Prasetyo', 
                'nis' => '20398',
                'gender' => 'L',
                'rombel' => 'SijaA',
                'alamat' => 'Berbah',
                'kontak' => '81234567890',
                'email' => 'aryok@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Angelina Thithis Sekar Langit', 
                'nis' => '20396',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Prambanan',
                'kontak' => '81234567890',
                'email' => 'thithis@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Aulia Maharani', 
                'nis' => '20400',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Maguwo',
                'kontak' => '81234567890',
                'email' => 'aul@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Intan Luvia Hisanah', 
                'nis' => '20414',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Jalan Kaliurang',
                'kontak' => '81234567890',
                'email' => 'intan@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Jardella Anggun Lavatektonia', 
                'nis' => '20417',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Jalan Kaliurang',
                'kontak' => '81234567890',
                'email' => 'della@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Kaysa Aqila Amta', 
                'nis' => '20419',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Turi',
                'kontak' => '81234567890',
                'email' => 'kayes@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Meidinna Tiara Pramudhita', 
                'nis' => '20423',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Jalan Kaliurang',
                'kontak' => '81234567890',
                'email' => 'memed@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Marcellinus Christo Pradipta', 
                'nis' => '20422',
                'gender' => 'L',
                'rombel' => 'SijaA',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'christo@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Naufelirna Subkhi Ramadhani', 
                'nis' => '20434',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Klaten',
                'kontak' => '81234567890',
                'email' => 'naufel@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Rosyidah Muthmainnah', 
                'nis' => '20448',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'rosyi@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Gabriel Possenti Genta Bahana Nagari', 
                'nis' => '20410',
                'gender' => 'L',
                'rombel' => 'SijaA',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'genta@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Nafisya Rhea Prayasti', 
                'nis' => '20433',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Bantul',
                'kontak' => '81234567890',
                'email' => 'rhea@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Farcha Amalia Nugrahaini', 
                'nis' => '20408',
                'gender' => 'P',
                'rombel' => 'SijaA',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'caca@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Tsabita Irene Adielia', 
                'nis' => '20455',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'tsabita@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Vicentius Reynara Ezratama', 
                'nis' => '20456',
                'gender' => 'L',
                'rombel' => 'SijaB',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'reynara@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Noveryan Putra Pamungkas', 
                'nis' => '20436',
                'gender' => 'L',
                'rombel' => 'SijaB',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'noveryan@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Nabila Nur Azizah', 
                'nis' => '20432',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'nabila@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'Thara Bunga Novriyansyah', 
                'nis' => '20454',
                'gender' => 'P',
                'rombel' => 'SijaB',
                'alamat' => 'Sleman',
                'kontak' => '81234567890',
                'email' => 'thara@gmail.com',
                'status_lapor_pkl'=> false,
            ],
        ]);
    }
}
